//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NguyenPhuNam_Project2_2210900047.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINH_LUAN
    {
        public int MaBL { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string Tieu_de { get; set; }
        public string Noi_dung { get; set; }
        public byte[] Ngay_BL { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
