//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NguyenPhuNam_Project2_2210900047.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINH_ANH
    {
        public int MaHA { get; set; }
        public string Ten_file_anh { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
        public Nullable<int> MaSP { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
