//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NguyenPhuNam_Project2_2210900047.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON()
        {
            this.CT_HOA_DON = new HashSet<CT_HOA_DON>();
        }
    
        public int MaHD { get; set; }
        public System.DateTime Ngay_HD { get; set; }
        public string Hoten_nguoinhan { get; set; }
        public string Diachi_nguoinhan { get; set; }
        public string Dienthoai_nguoinhan { get; set; }
        public string Diachi_email { get; set; }
        public Nullable<System.DateTime> Ngay_giao_hang { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaPTVC { get; set; }
        public Nullable<int> MaPTTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOA_DON> CT_HOA_DON { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual PT_THANH_TOAN PT_THANH_TOAN { get; set; }
        public virtual PT_VAN_CHUYEN PT_VAN_CHUYEN { get; set; }
    }
}
