//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NguyenPhuNam_Project2_2210900047.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIEN_HE
    {
        public int MaLH { get; set; }
        public string Tieu_de { get; set; }
        public string Dia_chi { get; set; }
        public string Dien_thoai { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string Logo { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    }
}
