//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NguyenPhuNam_Project2_2210900047.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN_PHAM()
        {
            this.BINH_LUAN = new HashSet<BINH_LUAN>();
            this.HINH_ANH = new HashSet<HINH_ANH>();
            this.SAN_PHAM_CT = new HashSet<SAN_PHAM_CT>();
        }
    
        public int MaSP { get; set; }
        public string Ten_sp { get; set; }
        public string Mo_ta { get; set; }
        public string Thong_tin { get; set; }
        public double Gia_goc { get; set; }
        public Nullable<double> Gia_giam_gia { get; set; }
        public int Luot_xem { get; set; }
        public Nullable<System.DateTime> Ngay_cap_nhat { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
        public Nullable<int> MaLSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINH_LUAN> BINH_LUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINH_ANH> HINH_ANH { get; set; }
        public virtual LOAI_SAN_PHAM LOAI_SAN_PHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAN_PHAM_CT> SAN_PHAM_CT { get; set; }
    }
}
